services:

  kafka:
    image: bitnami/kafka:3.7.1
    container_name: kafka
    networks:
      - kafka
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
      - 9999:9999
    restart: always
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - JMX_PORT=9999
    volumes:
      - kafka-logdir:/bitnami/kafka/data
      
  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    restart: always
    depends_on:
      - kafka
    networks:
      - kafka
    ports:
      - 9308:9308
    command: --kafka.server=kafka:9092

  jmx-exporter:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter
    restart: always
    depends_on:
      - kafka
    networks:
      - kafka
    ports:
      - 5556:5556
    volumes:
      - ./jmx-exporter:/etc/jmx-exporter
    command: 
      - "5556"
      - "/etc/jmx-exporter/jmx-exporter-config.yml"

volumes:
  kafka-logdir:

networks:
  kafka:
    driver: bridge
