services:

  zookeeper:
    image: bitnami/zookeeper:3.9.2
    container_name: zookeeper
    restart: always
    user: root
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-data:/bitnami/zookeeper"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT_NUMBER=2181
      - ZOO_TLS_CLIENT_AUTH=none
    networks:
      - kafka
      
  kafka1:
    image: bitnami/kafka:3.7.1
    container_name: kafka
    user: root
    ports:
      - 9092:9092
      - 9094:9094
      - 9999:9999
    restart: always
    depends_on: 
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
      - JMX_PORT=9999
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.17.0.1:9092,EXTERNAL://192.168.1.107:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka-data:/bitnami
    networks:
      - kafka
      
  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    restart: always
    depends_on:
      - kafka1
    ports:
      - 9308:9308
    command: --kafka.server=kafka:9092
    networks:
      - kafka

  jmx-exporter:
    image: bitnami/jmx-exporter:latest
    container_name: jmx-exporter
    restart: always
    depends_on:
      - kafka1
    ports:
      - 5556:5556
    volumes:
      - ./jmx-exporter:/etc/jmx-exporter
    command: 
      - "5556"
      - "/etc/jmx-exporter/jmx-exporter-config.yml"
    networks:
      - kafka

volumes:
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local

networks:
  kafka:
    driver: bridge
